package network

// Type of Service
const (
	IPV4_ST_PRE_ROUTINE        = 0
	IPV4_ST_PRE_PRIORITY       = 1 << 5
	IPV4_ST_PRE_IMMEDIATE      = 2 << 5
	IPV4_ST_PRE_FLASH          = 3 << 5
	IPV4_ST_PRE_FLASH_OVERRIDE = 4 << 5
	IPV4_ST_PRE_CRI_ECP        = 5 << 5
	IPV4_ST_PRE_INNET_CTRL     = 6 << 5
	IPV4_ST_PRE_NET_CONTROL    = 7 << 5

	IPV4_ST_LOW_DELAY       = 16
	IPV4_ST_HIGH_THROUGHPUT = 8
	IPV4_ST_HIGH_RELIBILITY = 4
)

// Flags
const (
	IPV4_FLAG_DONT_FRAG  = 2
	IPV4_FLAG_MORE_FRAGS = 1
)

// Protocol
const (
	IPV4_PRO_ICMP        = 1
	IPV4_PRO_GATEWAY     = 3
	IPV4_PRO_CMCC_MON    = 4
	IPV4_PRO_ST          = 5
	IPV4_PRO_TCP         = 6
	IPV4_PRO_UCL         = 7
	IPV4_PRO_SECURE      = 9
	IPV4_PRO_BBN_RCC_MON = 10
	IPV4_PRO_NVP         = 11
	IPV4_PRO_PUP         = 12
	IPV4_PRO_PLURIBUS    = 13
	IPV4_PRO_TELENET     = 14
	IPV4_PRO_XNET        = 15
	IPV4_PRO_CHAOS       = 16
	IPV4_PRO_UDP         = 17
	IPV4_PRO_MULT        = 18
	IPV4_PRO_DCN         = 19
	IPV4_PRO_TAC_MON     = 20
	IPV4_PRO_LOCAL_NET   = 63
	IPV4_PRO_SATNET      = 64
	IPV4_PRO_MIT         = 65
	IPV4_PRO_SATNET_MON  = 69
	IPV4_PRO_IPCU        = 71
	IPV4_PRO_BSATNET_MON = 76
	IPV4_PRO_WID_MON     = 78
	IPV4_PRO_WID_EXPAK   = 79
)

const (
	SIZEOF_IPV4_HEADER = 20
)
